/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package narnia;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Objects;
import java.util.Random;
import java.util.Scanner;
import java.util.StringTokenizer;

/**
 * Manages Ships of the cruise
 * @author sharanya
 */
public class Ship {

    int shipNo;
    String shipName;
    float shipWeight;
    int shipYear;
    public int shipCapacity;
    int count = 0;
    public static int conflict = 0;
    static int noofPassengers;
    static int noofSailors;
    Boolean[] blockedl = new Boolean[100];// To check if a ship has already been booked or not

    //ArrayList<Passengers> passengerobj = new ArrayList<Passengers>(200);
    static ArrayList<Integer> sailorc = new ArrayList<Integer>(20);

    int x1;
    static int j = 0;

    public void Ship() {
        for (int i = 0; i < 100; i++) {
            blockedl[i] = Boolean.FALSE;
        }

    }

   /**
    * Sets sailor data, calls corresponding inherited class objects and calls Sailor class' methods
    */
    public void setSailor() {
        

        Sailor sail = new Sailor();
        Random r = new Random();
        int cookcount = r.nextInt(3 - 0) + 1; //Every ship has 1 to 3 cooks, to 3 engineers, 4 supervisors, 3 sailors under each supervisor and 1 to 2 doctors
        int engcount = r.nextInt(3 - 0) + 1;
        int supervisorcount = 4, sailorcount = 12, doccount = r.nextInt(3 - 1) + 1;
        noofSailors=cookcount + engcount + supervisorcount + sailorcount + doccount;
        noofPassengers = shipCapacity - (cookcount + engcount + supervisorcount + sailorcount + doccount);
        if (noofPassengers < 15) {
            noofPassengers = 16;
        }
        
        ArrayList<Sailor> sailobj = new ArrayList<Sailor>(cookcount + engcount + supervisorcount + sailorcount + doccount); //Creates and array list according to number of dsilors
        sailorc.add(j++, (cookcount + engcount + supervisorcount + sailorcount + doccount - 1));
        

        sail.setData(0);// Sets captain Object

        while (cookcount > 0) {
            sail.setData(1);
            cookcount--; //Sets cooks
            
        }
        while (engcount > 0) {
            sail.setData(2); //Sets engineers
            engcount--;
            
        }
        while (supervisorcount > 0) {
            sail.setData(3); // sets supervisors
            supervisorcount--;
           
        }
        while (sailorcount > 0) {
            sail.setData(4); //Sets sailors
            sailorcount--;
          
        }

        while (doccount > 0) {
            sail.setData(5); //Sets Doctors
            doccount--;
            
        }
    
        sailobj.add(sail); //adds sialor objects to array list

    }

    /**
     * Sets passengers according to the  umber of passengers value entered by user or generated by system
     */
    public void setPassengers() {

        Passengers passenger = new Passengers();
        System.out.println("\nWould you like to enter the number of passengers for the cruise? Enter Y to input the number, any other key for random addition of passsengers");
        Scanner sc = new Scanner(System.in); Scanner sc1 = new Scanner(System.in);
        String a = sc.nextLine();//Prompts user to enter a value for no of users
        if (!a.equals("Y")) {
            for (int i = 0; i < noofPassengers; i++) {

                passenger.setData();

            }

        } else {
            
            System.out.println("\nEnter the number of passengers you wish to have:\n");
            noofPassengers=sc1.nextInt();
            for (int i = 0; i < noofPassengers; i++) {//  getPassengersData();
                         passenger.setData();
            }
        }

    }

    /**
     * Calls Ports objects and sets ports of call
     */

    public void setPort() {

        Port port = new Port();

        ArrayList<Port> portobj = new ArrayList<Port>(15);
        
        for (int i = 0; i < 15; i++) {

            port.setData(shipCapacity);  //Based on Capacity of SHips, Port objects are assigned value such as docking fees
            portobj.add(port);
        }
    }

    //Sets Ship object and assigns value to ship attributes
    public void setData() {
        try {

            int scloop = 1;
            BufferedReader in = new BufferedReader(new FileReader("Ship.txt")); // Reads Ship data from Ship.txt file
            String s;
            Random r1 = new Random();
            x1 = r1.nextInt(20 - 0) + 0;
            while (Objects.equals(blockedl[x1], Boolean.TRUE)) {
                System.out.println("Ship No" + (x1 + 1) + " is sailing on another cruise"); //Checks if SHip has already been chosen or not
                x1 = r1.nextInt(20 - 0) + 0;
                conflict++;
            }

            //System.out.print("Ship No: " + (x1 + 1) + " ");
            s = in.readLine();
            while (scloop <= x1) {
                s = in.readLine();
                scloop++;
            }
            s = in.readLine();

            StringTokenizer str = new StringTokenizer(s, "|"); //Tokenizes the read string  and assigns values to each of the ship attributes 
            shipNo = Integer.parseInt(str.nextElement().toString());
            shipName = str.nextElement().toString();
            shipWeight = Integer.parseInt(str.nextElement().toString());
            shipYear = Integer.parseInt(str.nextElement().toString());
            shipCapacity = Integer.parseInt(str.nextElement().toString());

            blockedl[x1] = Boolean.TRUE;
            System.out.println("                              Welcome to Narnia Cruises"); //Prints chosen Ship Data to console
            System.out.println("\n\nA new Cruise has been introduced, details below:");
            System.out.printf("\n%-20s %-20s %-20s %-20s %-20s\n", "Ship No", "Ship Name", "Ship Weight", "Ship Year", "Ship Capacity");
            System.out.printf("\n%-20d %-20s %-20.2f %-20d %-20d\n", shipNo, shipName, shipWeight, shipYear, shipCapacity);

        } catch (IOException | NumberFormatException e) {
        }
    }

    void releaseShip(int pos) {
        blockedl[x1] = Boolean.TRUE;

    }

    public int getShipNo() {
        return shipNo;
    }

    public String getShipName() {
        return shipName;
    }

    public float getShipWeight() {
        return shipWeight;
    }

    public int getShipYear() {
        return shipYear;
    }

    public int getShipCapacity() {
        return shipCapacity;
    }

    public int getCount() {
        return count;
    }

}
